defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

sass:
  load_paths:
    - _sass
    - _sass/node_modules

# O que excluir do build (se diretório, usar a / final):
exclude:
  - _config.yml
  - Gemfile
  - Gemfile.lock
  - INSTRUCOES
  - jekyll-theme-cs50.gemspec
  - lib/
  - package.json
