source "https://rubygems.org"
gemspec

# Versão do Jekyll a ser utilizada (manter comentado se utilizar GitHub Pages)
#gem "jekyll", "~> 4.2.2"

# Se usar GitHub Pages:
#gem "jekyll-theme-cs50", group: :jekyll_plugins, git: "https://github.com/cs50/jekyll-theme-cs50", branch: "develop"

# Temas disponíveis (descomentar se necessário):
#gem "minima", "~> 2.5"

# Outros plugins a serem ativados:
group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
end

# Windows (sempre ele!) não tem arquivos "zoneinfo",
# entao vamos agregar tudo com a gem tzinfo-data e
# outras bibliotecas associadas:
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# "Performance-booster" para monitorar diretórios
# ao usar Windows:
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Mantém a gem `http_parser.rb` na versão `v0.6.x`
# durante os builds do JRuby, já que novas versõe~s das gem
# não têm um  builds since newer versions of the gem
# não têm uma contrapartida Java:
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

# Usa a gem webrick para poder usar o servidor local
# durante o desenvolvimento:
gem "webrick", "~> 1.7"

# Usar o CodeRay syntax highlighter com o Kramdown:
#gem "kramdown-syntax-coderay", "~> 1.0"
